name: Upload S3
description: 'Upload all files from given directory (default ./s3) to S3'
author: Alexey Chekulaev
inputs:
  access-key-id:
    required: true
    description: AWS access key id
  secret-access-key:
    required: true
    description: AWS secret access key
  session-token:
    required: true
    description: AWS session token
  source-dir:
    required: false
    default: s3
    description: directory at local file system
  bucket:
    required: true
    description: s3 bucket name
  bucket-dir:
    required: true
    description: s3 bucket directory
  tags:
    required: false
    description: tags to be added to s3 objects. Format is key1=value1&key2=value2
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'

# Node 20 is max as of Mar 2024
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-javascript-action
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions