name: Upload S3
description: 'Upload all files from given directory (default ./s3) to S3'
author: Alexey Chekulaev
inputs:
  access-key-id:
    required: true
    description: AWS access key id
  secret-access-key:
    required: true
    description: AWS secret access key
  session-token:
    required: true
    description: AWS session token
  bucket:
    required: true
    description: s3 bucket name
  bucket-dir:
    required: false
    description: s3 bucket directory to place - 'bucket/bucket-dir/repo-name/version', empty by default
  dev-release:
    required: false
    description: 'if true, will upload to "dev" bucket, otherwise to "prod" bucket'
    default: false
  versions:
    required: true
    description: ex - 1.2.4,1.2,1,latest; could be 2.0-beta, fix-135
runs:
  using: 'node24'
  main: 'dist/index.js'
