name: Upload S3
description: 'Upload all files from given directory to S3'
author: Alexey Chekulaev
inputs:
  access-key-id:
    required: true
    description: AWS access key id
  secret-access-key:
    required: true
    description: AWS secret access key
  session-token:
    required: true
    description: AWS session token
  source-dir:
    required: true
    description: directory at local file system
  bucket:
    required: true
    description: s3 bucket name
#  tags:
#    required: false
#    description: tags to be added to s3 objects
runs:
  using: 'node20'
  main: 'dist/index.js'
