name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      artifacts: true

  # 1. Generate new version - based on latest tag + git commit message: #major, #minor, #patch
  # 2. Commit and push
  # 3. Push two tags: new (generated) version and 'latest'
  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }} # Admin PAT to bypass push protection on 'main' branch

      - name: Download artifacts
        uses: actions/download-artifact@v4
        # after this we have changes in file dist/index.js

      # generate new version, commit and push commit + tags
      - name: Release
        id: release
        uses: agilecustoms/gha-release@main

      - name: Summary
        run: echo "### Released ${{ steps.release.outputs.version }} :pushpin:" >> $GITHUB_STEP_SUMMARY
