name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      artifacts: true

  # 1. Generate new version - based on latest tag + git commit message: #major, #minor, #patch
  # 2. Commit and push
  # 3. Push two tags: new (generated) version and 'latest'
  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }} # Admin PAT to bypass push protection on 'main' branch

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Commit and push
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5 # https://github.com/stefanzweifel/git-auto-commit-action
        with:
          commit_message: "Rebuild dist/index.js [skip ci]" # avoid triggering of another build-and-release workflow

      # generate new version and push two tags: new (generated) version and 'latest'
      - name: Release
        id: release
        uses: agilecustoms/gha-release@main
        with:
          gh_token: ${{ secrets.GH_ACTIONS_TOKEN }} # Admin PAT to push tags in 'main' branch
          upload_s3: false

      - name: Summary
        run: echo $([ "${{ steps.commit.outputs.changes_detected }}" == 'true' ] && echo "### New version released" || echo "### No changes") >> $GITHUB_STEP_SUMMARY
