name: Build

on:
  push:
    branches-ignore:
      - main
  workflow_call: # can be called from 'verify-and-release' workflow

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Integration Tests
        run: npm run integration-test

      # Idea is that if all tests pass, then it deserve to be built
      # It doesn't matter for 'verify' workflow, but it does for 'verify-and-release' workflow
      #  so I don't need to download all dependencies again
      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist # take everything from dist/ folder
          name: dist #  and create artifact named dist (so later on the download action will create <repo-root>/dist/ folder)
