name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Tests
        run: |
          npm ci
          npm run test

      - name: Integration Tests
        run: npm run integration-test