name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/f-build.yml

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Debug
        run: git status

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5 # https://github.com/stefanzweifel/git-auto-commit-action
        with:
          commit_message: "Rebuild dist/index.js"
