name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/f-build.yml

  Release:
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write # to do 'push' at the end of this job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Commit and push
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5 # https://github.com/stefanzweifel/git-auto-commit-action
        with:
          commit_message: "Rebuild dist/index.js"

      - name: Summary
        run: echo $([ "${{ steps.commit.outputs.changes_detected }}" == 'true' ] && echo "### New version released" || echo "### No changes") >> $GITHUB_STEP_SUMMARY
