name: Manual test

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'AWS S3 bucket'
        required: true
        default: 'agilecustoms-tt-web-dist'
      bucket-dir:
        description: 'AWS account dist'
        required: true
        default: abc

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: creds
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_DIST }}:role/ci/builder
          output-credentials: true

      - name: Upload S3
        uses: agilecustoms/gha-upload-s3@main
        with:
          access-key-id: ${{ steps.creds.outputs.aws-access-key-id }}
          secret-access-key: ${{ steps.creds.outputs.aws-secret-access-key }}
          session-token: ${{ steps.creds.outputs.aws-session-token }}
          source-dir: 'dist'
          bucket: ${{ github.event.inputs.bucket }}
          bucket-dir: ${{ github.event.inputs.bucket-dir }}
          tags: Release=true&Tag=1.1
