name: Manual test

on:
  workflow_dispatch:

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Upload S3
        uses: agilecustoms/gha-upload-s3@main
        with:
          source_dir: 'dist'
          bucket: 'agilecustoms-tt-web-dist'
